name: java-ci
on: [push, pull_request]
jobs:
  test-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Maven tests
        run: mvn -q -f java-testng-extent/pom.xml test
      - name: Upload Extent report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: java-extent-report
          path: java-testng-extent/reports/
