name: python-ci
on: [push, pull_request]
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python-pytest/requirements.txt
      - name: Run pytest
        run: |
          cd python-pytest
          pytest -m "ui or api" --headless --browser chrome --html=reports/report.html --self-contained-html
      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-pytest-report
          path: python-pytest/reports/
